steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/birthdaycalc:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/birthdaycalc:$COMMIT_SHA']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'birthdaycalc'
      - '--image'
      - 'gcr.io/$PROJECT_ID/birthdaycalc:$COMMIT_SHA'
      - '--region'
      - 'us-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '1'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1000m'
      - '--port'
      - '5000'

images:
  - 'gcr.io/$PROJECT_ID/birthdaycalc:$COMMIT_SHA'
